# Generated by Django 5.0.6 on 2024-06-15 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_examcenter_studentexamcenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyExamCenter',
            fields=[
            ],
            options={
                'ordering': ['cname'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('school.examcenter',),
        ),
    ]
