# Generated by Django 5.0.6 on 2024-05-24 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, validators=[django.core.validators.MinLengthValidator(4)])),
                ('email', models.EmailField(max_length=70)),
                ('password', models.CharField(max_length=70)),
                ('repassword', models.CharField(max_length=70)),
            ],
        ),
    ]
