# Generated by Django 5.0.6 on 2024-05-24 10:20

import django.core.validators
import enroll.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=70, validators=[django.core.validators.MinLengthValidator(4), enroll.models.starts_with_a]),
        ),
    ]
